### ISSUE TITLE
I have created a dart version of mudderjs. Please tell me what do you think about it.

### ISSUE THREAD

**Issue by tiagocpeixoto** [fasiha/mudderjs#13]
You can check it @ https://pub.dev/packages/mudder_dart.

**Comment by fasiha** [comment]
First thought: 🥳🤩 coooooooool!!!

Second thought: 😱🤭 someone read the extremely confusing and undocumented `longLinspace` and `roundFraction` functions!!!

Bottom line, thank you for your hard work! I'll add a note to the README pointing to this port.

Do you love Dart? Do you use this with Flutter, or just in the backend? Any tips you'd give—I've read some of the Dart and Flutter documentation and of course it looks great, but you know how you don't know where a very nice pair of shoes pinches your foot until you've worn it for a couple of days.

**Comment by tiagocpeixoto** [comment]
To be honest (1), I can't say that I love Dart. I have a hobby project that consists of an API (backend) and two clients. 
The API (typescript + nodejs) stores and sort items based on a lexicographically-spaced field.
One of the clients is implemented with React Native and Typescript. The other one is based on Flutter and Dart. 
I use the [optimistic UI](https://uxdesign.cc/the-optimistic-ui-with-react-f1420e317d54) approach to save data on both clients, so I have to use mudderjs as a dependency on the first one (React Native client). For the latest (Flutter client), I ported your project as you already know. 

To be honest (2), I'm being more productive with React Native than with Flutter. The former has more support from the community and I suspect that React-Native + Typescript combination allows me to be more agile than with Flutter + Dart.

**Comment by fasiha** [comment]
Thank you that's really interesting, I appreciate the time and thought you put into putting your experience into words!
